### ISSUE TITLE
[PE-D][Tester B] The Help button provided the wrong URL

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-4/tp#112]
After click HELP button it shows

![image.png](https://raw.githubusercontent.com/ZHANGTIANYAO1/ped/main/files/2de91c8b-3f64-4e2c-a206-68763afb8103.png)

After click the `Copy URL` button, the URL copyed is `https://se-education.org/addressbook-level3/UserGuide.html`
Which is not the correct URL

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZHANGTIANYAO1/ped#1

**Comment by DominicFuMJ** [comment]
Duplicate issue #116
