### ISSUE TITLE
[PE-D][Tester A] Help Page does not link to Moddie User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-4/tp#116]
The help button shows the following pop up, but the link is incorrect - not updated, still showing original AB3 user guide - requires updating on the code side as well as on the UG file

![image.png](https://raw.githubusercontent.com/Kappaccinoh/ped/main/files/72406a9a-495f-4672-8e83-7639e1858008.png)

![image.png](https://raw.githubusercontent.com/Kappaccinoh/ped/main/files/e5bbfd89-4308-4c18-89e9-d2407c9b41c2.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Kappaccinoh/ped#1

**Comment by DominicFuMJ** [comment]
Done
