### ISSUE TITLE
[PE-D][Tester A] User Guide lacks clarity on how duplicate contacts are determined and handled

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-4/tp#126]
Not sure if this is a bug, but is this expected behaviour? That contacts of every detail the same just that the names are not case sensitive is recognised as distinct entries?

Would checking for case sensitivity be a good check to have or rather maybe this should be explicitly mentioned in the user guide that contacts with same fields are allowed as long as the contact name is different 

![image.png](https://raw.githubusercontent.com/Kappaccinoh/ped/main/files/da8702e9-76d5-4dc0-a01e-c418b48a3968.png)

in this case I have 2 contacts that are effectively the same

A little more testing shows that the main differentiating factor is based off phone number and email

![image.png](https://raw.githubusercontent.com/Kappaccinoh/ped/main/files/c2b6397a-c1cd-48ab-bdf2-ffbdcee26ca3.png)

while this is fine, i might imagine users to be confused as to how duplicate contacts are differentiated and what fields does the addressbook take into account.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Kappaccinoh/ped#3

**Comment by DominicFuMJ** [comment]
Done
