### ISSUE TITLE
[PE-D][Tester A] Selecting person for Schedule UI requires mouse clicking action (feature flaw?)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-4/tp#151]
Since the main target user of this tP is CLI focused, is displaying the persons on the schedule ui section using a clickable drop down list using a mouse perhaps a good idea?

![image.png](https://raw.githubusercontent.com/Kappaccinoh/ped/main/files/7925fa09-8519-49a9-b3f6-6cc2a0f617e5.png)

my suggestion is that it be better if this displaying or selecting of person's schedules was done as a command through the CLI instead to be consistent with the target audience

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Kappaccinoh/ped#11

**Comment by DominicFuMJ** [comment]
Plan enhancement: Add command to view schedules
