### ISSUE TITLE
[PE-D][Tester D] Functionality Bug - Schedule Display

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-4/tp#157]
This could potentially be a feature flaw but I assume that the issue lies in different computers causing the UI to be not functional.

I was unable to get the schedule display to be working with dummy data.
![image.png](https://raw.githubusercontent.com/javierng2knus/ped/main/files/7b2811bf-c706-4c7e-a6d4-2dbc26e02fd1.png)

The starting data was not being display as well.
![image.png](https://raw.githubusercontent.com/javierng2knus/ped/main/files/54ccbd55-9c03-45e6-9f0d-379a9d449de6.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: javierng2knus/ped#8

**Comment by DominicFuMJ** [comment]
Remove the Test Mod

**Comment by DominicFuMJ** [comment]
This is because the test date for the dummy data and the input data was not for the current week. We stated in the user guide that it will only display the schedule in the current week. New functionality will be added to transverse the weeks.
